# Generated by Django 6.0 on 2025-12-25 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_documentchunk_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'DOCX Document'), ('image', 'Image (PNG/JPG/JPEG)')], max_length=20)),
                ('cloudinary_url', models.URLField(max_length=500)),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.asset'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['asset', 'created_at'], name='document_ch_asset_i_0c78e3_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'created_at'], name='assets_user_id_1cc8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'asset_type'], name='assets_user_id_c351cd_idx'),
        ),
    ]
